### ISSUE TITLE
titlecase==2.4 ImportingError

### ISSUE THREAD

**Issue by see7e** [shacker/gtd#15]
```bash
Collecting titlecase==2.4 (from -r requirements.txt (line 276))
  Downloading titlecase-2.4.tar.gz (14 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting toml==0.10.2 (from -r requirements.txt (line 279))
  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting tomli==2.0.1 (from -r requirements.txt (line 283))
  Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting tomlkit==0.11.8 (from -r requirements.txt (line 290))
  Downloading tomlkit-0.11.8-py3-none-any.whl (35 kB)
Collecting typing-extensions==4.6.3 (from -r requirements.txt (line 294))
  Downloading typing_extensions-4.6.3-py3-none-any.whl (31 kB)
Collecting webencodings==0.5.1 (from -r requirements.txt (line 302))
  Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Collecting wrapt==1.15.0 (from -r requirements.txt (line 306))
  Downloading wrapt-1.15.0-cp311-cp311-win_amd64.whl (36 kB)
Collecting tzdata (from django==4.2.2->-r requirements.txt (line 29))
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    tzdata from https://files.pythonhosted.org/packages/a3/fb/52b62131e21b24ee297e4e95ed41eba29647dad0e0051a92bb66b43c70ff/tzdata-2023.4-py2.py3-none-any.whl (from django==4.2.2->-r requirements.txt (line 29))
```

python --version
Python 3.11.4
pip --version
pip 23.3.2 from C:\...\gtd-master\.venv\Lib\site-packages\pip (python 3.11)

**Comment by see7e** [comment]
Added pip-tools with: `python -m pip install pip-tools` and tried to generate new hashes with `pip-compile --generate-hashes --verbose --output-file=requirements.txt base.in`.

Now if run `pip install -r requirements.txt` it installs everything. 😄 

```bash
Successfully installed asgiref-3.7.2 astroid-2.15.5 bleach-6.0.0 dill-0.3.6 dj-database-url-2.0.0 django-4.2.2 django-autocomplete-light-3.9.7 django-extensions-3.2.3 django-simple-deploy-0.5.15 django-todo-2.5.0 factory-boy-3.2.1 faker-18.10.1 flake8-6.0.0 gunicorn-20.1.0 html2text-2020.1.16 iniconfig-2.0.0 isort-5.12.0 lazy-object-proxy-1.9.0 mccabe-0.7.0 mypy-1.3.0 mypy-extensions-1.0.0 packaging-23.1 platformdirs-3.5.3 pluggy-1.0.0 psycopg2-binary-2.9.6 pycodestyle-2.10.0 pyflakes-3.0.1 pylint-2.17.4 pytest-7.3.2 pytest-django-4.5.2 python-dateutil-2.8.2 six-1.16.0 sqlparse-0.4.4 titlecase-2.4 toml-0.10.2 tomlkit-0.11.8 typing-extensions-4.6.3 tzdata-2023.4 webencodings-0.5.1 wrapt-1.15.0
```

**Comment by shacker** [comment]
@see7e Your issue was missing introductory information, but I gather you were trying to install gtd per the instructions? I just made a new .venv and tried it per instructions and it worked perfectly, with no issues.

```
cd ~/dev
git clone git@github.com:shacker/gtd.git
cd gtd
python3.11 -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt
```

I did not encounter the tzdata issue you are seeing. I am on py 3.11.4 and pip 23.1.2

But it can't hurt to update requirements from time to time, so this is a good kick in the pants to get that done. OK done! Thanks for the note.

**Comment by see7e** [comment]
Sorry for the short explanation about the issue, was a long day of looking up about projects with similar scope, I'm trying to understand the mechanisms so it could help me I'm the building process of a similar project. But appart from that this error was showing off when I was trying to install the dependencies, as my comment below was after trying the steps that led me to resolve the mentioned issue.

I wasn't trying to be rude, wanted only to help, if someone stumbled in a similar situation.

**Comment by shacker** [comment]
@see7e Not all, and no worries! Thanks again for the issue - glad we got it resolved for you. Cheers.
