### ISSUE TITLE
form.non_field_errors doesn't always exist in base.html

### ISSUE THREAD

**Issue by multun** [shacker/gtd#5]
https://github.com/shacker/gtd/blob/master/project/templates/base.html#L77
running with debugging enabled results in noisy logs. non field errors should be displayed on a per-form basis, or in a block. what do you think ?

**Comment by shacker** [comment]
I'm not quite clear on what you would like to see changed. Are you saying that your base.html doesn't include `form.non_field_errors` and you don't want to add it to your base template for some reason? If not, why not? This is a reference/example implementation. What do you suggest that I change?

**Comment by shacker** [comment]
No response from the OP and request is unclear. Closing.
