### ISSUE TITLE
pyparsing library being used is no longer available

### ISSUE THREAD

**Issue by daoudsleiman** [shacker/gtd#7]
https://stackoverflow.com/a/57202537/7232885

Used pyparsing version 2.4.1.1 and got it to run.

**Comment by james1293** [comment]
I'm not an expert at finding python dependencies in a project, but is pyparsing a direct dep of this project? Or is it a dep of one of the deps?

**Comment by daoudsleiman** [comment]
i think it is a dep of one of the deps

**Comment by shacker** [comment]
There is no reference to `pyparsing` in either the gtd or the django-todo repos. I did a full `pipenv graph` on both projects and did not see that lib mentioned as a dependency of anything. 

Where you opting to use the mail tracker feature of django-todo when you hit this error? Or was it happening on all views? Do you have the traceback by chance?

**Comment by shacker** [comment]
No response from the OP, and I cannot reproduce. Closing.
